package com.itany.nmms.entity;

public class Product {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_product.product_id
     *
     * @mbggenerated Fri Nov 02 09:01:11 CST 2018
     */
    private Integer productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_product.product_no
     *
     * @mbggenerated Fri Nov 02 09:01:11 CST 2018
     */
    private String productNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_product.name
     *
     * @mbggenerated Fri Nov 02 09:01:11 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_product.price
     *
     * @mbggenerated Fri Nov 02 09:01:11 CST 2018
     */
    private Double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_product.image
     *
     * @mbggenerated Fri Nov 02 09:01:11 CST 2018
     */
    private String image;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_product.product_type_id
     *
     * @mbggenerated Fri Nov 02 09:01:11 CST 2018
     */
    private Integer productTypeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_product.product_id
     *
     * @return the value of sys_product.product_id
     *
     * @mbggenerated Fri Nov 02 09:01:11 CST 2018
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_product.product_id
     *
     * @param productId the value for sys_product.product_id
     *
     * @mbggenerated Fri Nov 02 09:01:11 CST 2018
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_product.product_no
     *
     * @return the value of sys_product.product_no
     *
     * @mbggenerated Fri Nov 02 09:01:11 CST 2018
     */
    public String getProductNo() {
        return productNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_product.product_no
     *
     * @param productNo the value for sys_product.product_no
     *
     * @mbggenerated Fri Nov 02 09:01:11 CST 2018
     */
    public void setProductNo(String productNo) {
        this.productNo = productNo == null ? null : productNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_product.name
     *
     * @return the value of sys_product.name
     *
     * @mbggenerated Fri Nov 02 09:01:11 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_product.name
     *
     * @param name the value for sys_product.name
     *
     * @mbggenerated Fri Nov 02 09:01:11 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_product.price
     *
     * @return the value of sys_product.price
     *
     * @mbggenerated Fri Nov 02 09:01:11 CST 2018
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_product.price
     *
     * @param price the value for sys_product.price
     *
     * @mbggenerated Fri Nov 02 09:01:11 CST 2018
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_product.image
     *
     * @return the value of sys_product.image
     *
     * @mbggenerated Fri Nov 02 09:01:11 CST 2018
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_product.image
     *
     * @param image the value for sys_product.image
     *
     * @mbggenerated Fri Nov 02 09:01:11 CST 2018
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_product.product_type_id
     *
     * @return the value of sys_product.product_type_id
     *
     * @mbggenerated Fri Nov 02 09:01:11 CST 2018
     */
    public Integer getProductTypeId() {
        return productTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_product.product_type_id
     *
     * @param productTypeId the value for sys_product.product_type_id
     *
     * @mbggenerated Fri Nov 02 09:01:11 CST 2018
     */
    public void setProductTypeId(Integer productTypeId) {
        this.productTypeId = productTypeId;
    }
}