package com.itany.nmms.entity;

public class ProductType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_product_type.id
     *
     * @mbggenerated Wed Oct 31 15:08:56 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_product_type.name
     *
     * @mbggenerated Wed Oct 31 15:08:56 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_product_type.status
     *
     * @mbggenerated Wed Oct 31 15:08:56 CST 2018
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_product_type.id
     *
     * @return the value of sys_product_type.id
     *
     * @mbggenerated Wed Oct 31 15:08:56 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_product_type.id
     *
     * @param id the value for sys_product_type.id
     *
     * @mbggenerated Wed Oct 31 15:08:56 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_product_type.name
     *
     * @return the value of sys_product_type.name
     *
     * @mbggenerated Wed Oct 31 15:08:56 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_product_type.name
     *
     * @param name the value for sys_product_type.name
     *
     * @mbggenerated Wed Oct 31 15:08:56 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_product_type.status
     *
     * @return the value of sys_product_type.status
     *
     * @mbggenerated Wed Oct 31 15:08:56 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_product_type.status
     *
     * @param status the value for sys_product_type.status
     *
     * @mbggenerated Wed Oct 31 15:08:56 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}