package com.itany.nmms.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.itany.nmms.entity.Staff;
import com.itany.nmms.entity.StaffExample;

public interface StaffDao {
	
	/**
	 * 用户登录
	 * @param loginName
	 * @param password
	 * @param role
	 * @param isValid
	 * @return
	 */
	Staff selectByLoginNameAndPassword(String loginName,String password,String role,Integer isValid);
	
	/**
	 * 条件查询
	 * @param staffParameter
	 * @return
	 */
	List<Staff> selectByParams(Staff staffParameter);
	
	
	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_staff
     *
     * @mbggenerated Thu May 03 13:49:09 CST 2018
     */
    int countByExample(StaffExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_staff
     *
     * @mbggenerated Thu May 03 13:49:09 CST 2018
     */
    int deleteByExample(StaffExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_staff
     *
     * @mbggenerated Thu May 03 13:49:09 CST 2018
     */
    int deleteByPrimaryKey(Integer staffId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_staff
     *
     * @mbggenerated Thu May 03 13:49:09 CST 2018
     */
    int insert(Staff record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_staff
     *
     * @mbggenerated Thu May 03 13:49:09 CST 2018
     */
    int insertSelective(Staff record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_staff
     *
     * @mbggenerated Thu May 03 13:49:09 CST 2018
     */
    List<Staff> selectByExample(StaffExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_staff
     *
     * @mbggenerated Thu May 03 13:49:09 CST 2018
     */
    Staff selectByPrimaryKey(Integer staffId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_staff
     *
     * @mbggenerated Thu May 03 13:49:09 CST 2018
     */
    int updateByExampleSelective(@Param("record") Staff record, @Param("example") StaffExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_staff
     *
     * @mbggenerated Thu May 03 13:49:09 CST 2018
     */
    int updateByExample(@Param("record") Staff record, @Param("example") StaffExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_staff
     *
     * @mbggenerated Thu May 03 13:49:09 CST 2018
     */
    int updateByPrimaryKeySelective(Staff record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_staff
     *
     * @mbggenerated Thu May 03 13:49:09 CST 2018
     */
    int updateByPrimaryKey(Staff record);
}
